export const translationKeys = {
  stats: "stats",
  currRating: "currRating",
  leaderboardRank: "leaderboardRank",
  gamesWon: "gamesWon",
  gamesLost: "gamesLost",
  totalGames: "totalGames",
  winPerc: "winPerc",
  general: "general",
  ranked: "ranked",
  rank: "rank",
  player: "player",
  rating: "rating",
  winLoss: "winLoss",
  history: "history",
  filter: "filter",
};
