export const translationKeys = {
  buttons: {
    join: "buttons.join",
    cancel: "buttons.cancel",
    add: "buttons.add",
  },
  errorMessages: {
    channelNameEmpty: "Channel name can not be empty!",
    passwordEmpty: "Password can not be empty",
    createRoomFailed: "Failed to create channel",
    joinRoomFailed: "Failed to join channel",
    joinRoomError: "Can't join this channel",
    inviteFailed: "Failed to invite user",
    editRoomFailed: "Failed to change room info",
    messageSendFail: "Failed to send message",
    leaveRoomFailed: "Failed to remove channel",
	banFailed: "Failed to ban user",
	muteFailed: "Failed to mute user",
	updateRoleFailed: "Failed to promote user",
	dmFail: "Failed to set up directmessaging",
	profileAccessFail: "Failed to access profile",
	playInviteFail: "Failed to invite to play",
	blockFail: "Failed to block User",
	unblockFail: "Failed to unblock User",
  },
  chat: "Chat",
  ranked: "Ranked",
  general: "General",
  userLeft: "left the channel",
  userJoined: "joined the channel",
  muted: "You have been muted for 30 seconds",
  passwordReq: "This channel requires a password",
  whisper: "Whisper",
  promote: "Promote",
  viewProfile: "View Profile",
  inviteToGame: "Invite to Game",
  mute: "Mute",
  ban: "Ban",
  block: "Block",
  unblock: "Unblock",
  gameMode: "Game Mode",
  public: "Public",
  private: "Private",
  protected: "Protected",
  createChannelTitle: "Create new channel",
  createChannelText: "Please enter channel name, accessibility and password.",
  name: "Name",
  access: "Access",
  password: "Password",
  add: "Add",
  cancel: "Cancel",
  classic: "Classic",
  mayhem: "Mayhem",
  hockey: "Hockey",
  joinChannelTitle: "Join existing channel",
  joinChannelText:
    "Please enter the name and password of the channel you want to Join.",
  join: "Join",
  create: "Create",
  channelInfo: "Channel Info",
  changePassword: "Change Password",
  changeName: "Change Name",
  status: "Status",
  you: "You",
  missing: "missing",
  inviteTo: "Invite to: ",
  remove: "Remove",
  invite: "Invite",
  leavePasswordEmpty: "Leave Password empty to remove Password protection",
  oldPassword: "Old Password",
  newNameOfChannel: "Enter new Name of the channel",
  newName: "New name",
  userName: "User-Name",
};
