version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    restart: always
    networks:
      - ft_transcendence

  nest:
    build:
      context: ./nest/
      dockerfile: nest.Dockerfile
    container_name: nest
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./nest/:/app/nest
    ports:
      - "8080:8080"
      - "3333:3333"
    depends_on:
      - postgres
    restart: always
    networks:
      - ft_transcendence

  ui:
    build:
      context: ./ui/
      dockerfile: ui.Dockerfile
    container_name: ui
    volumes:
      - ./ui/:/app
      - "/app/node_modules"
    ports:
      - "3000:3000"
    restart: always
    networks:
      - ft_transcendence
    depends_on:
      - nest

  nginx:
    build: ./reverse_proxy/
    container_name: reverse_proxy
    ports:
      - 8000:8000
    volumes:
      - ./ui/:/usr/share/nginx/html
      - ./reverse_proxy/conf/:/etc/nginx/conf.d
    networks:
      - ft_transcendence
    depends_on:
      - ui

networks:
  ft_transcendence:
    name: ft_transcendence
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"

volumes:
  postgres:
