export const translationKeys = {
  chat: "chat",
  ranked: "Ranked",
  general: "General",
  userLeft: "left the channel",
  userJoined: "joined the channel",
  muted: "You have been muted for 30 seconds",
  passwordReq: "This channel requires a password",
  whisper: "Whisper",
  promote: "Promote",
  viewProfile: "View Profile",
  inviteToGame: "Invite to Game",
  mute: "Mute",
  ban: "Ban",
  block: "Block",
  unblock: "Unblock",
  gameMode: "Game Mode",
  public: "Public",
  private: "Private",
  protected: "Protected",
  createChannelTitle: "Create new channel",
  createChannelText: "Please enter channel name, accessibility and password.",
  name: "Name",
  access: "Access",
  password: "Password",
  add: "Add",
  cancel: "Cancel",
  classic: "Classic",
  mayhem: "Mayhem",
  hockey: "Hockey",
};
